[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/nginx/access.log
    Tag               nginx.access
    Parser            nginx_json
    Refresh_Interval  5

[FILTER]
    Name    lua
    Match   nginx.access
    script  transform.lua
    call    transform_log

[OUTPUT]
    Name           kafka
    Match          nginx.access
    Brokers        192.168.1.14:30092
    Topics         logs-raw
    Format         json
    Timestamp_Key  timestamp
